### ISSUE TITLE
[BUG] Works with local install, not after pip install from PyPi

### ISSUE THREAD

**Issue by sfirke** [rogers-obrien-rad/clarity-python-sdk#9]
Hello, thanks for this package!  I need to pull data from some Clarity.io sensors and this looks like just what I need.

I installed the package with `pip install claripy-sdk` but then when I run `from claripy.clarity import Clarity` I get the error:
> ModuleNotFoundError: No module named 'claripy.clarity'

I had a friend try it on their machine (different setup) to make sure it wasn't me and he gets the same error.  Perhaps this package works when installed locally but isn't configured fully to run after a pip install?

EDIT: Indeed, if I clone the repo and then run `pip install .` then the above command from the README succeeds.  This may need some edits to work from a PyPi install?

**Comment by sfirke** [comment]
I did a little reading + LLM chatting and I wonder if `py_modules=find_packages()` in your setup.py file needs to be changed to `packages=find_packages()` ?  I don't have a way to validate that suggestion unfortunately.

I now have this package pulling data for a public-facing dashboard and plan to make it a permanent part of my workflow.  Let me know if you want a hand testing any fixes.

**Comment by sfirke** [comment]
ping @HagenFritz since I'm not sure if you're watching this repo to see this issue.  Is this something you're able to look into?

**Comment by HagenFritz** [comment]
@sfirke thanks for the ping, I have not been watching this repo. 

I am glad to hear that you were able to pull the data at least with a local clone. 

We are no longer working on the project we were using these sensors for and other more pressing matters have come up so I won't be able to look into this in the near future. Thank you for taking some time to try and debug the issue. If a get some free time, I will start with updating the setup.py file.

**Comment by sfirke** [comment]
Sounds good.  If you won't be using those sensors going forward and don't have a reason to work on the package, I might be interested in becoming a maintainer of the PyPI project to try to get it working.

**Comment by sfirke** [comment]
I've dug into this further.  Clarity has deprecated v1 of the API which this package uses.  They say it will be shut off this month.  I have written a new package with a small set of minimal functions that use v2 of the API: https://github.com/a2gov/clarityio

I'll close this issue as I no longer need it fixed.  Your package showed me that I wanted a workflow where I could use a Python package to pull the API data - thank you! 🙏
